baseURL = "https://yangzh1874.cn/"
languageCode = "zh-cn"
title = "My Research"
theme = "PaperMod"

[params]
    defaultTheme = "auto"
    # ä½ çš„ç®€ä»‹
    homeInfoParams.Title = "Hi there ğŸ‘‹"
    homeInfoParams.Content = "Focus on Computer Vision & AI in Agriculture."

    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/yourname"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  # è¿™é‡Œå¯¹åº”ä½ æƒ³è¦çš„ Datasets é¡µé¢
  [[menu.main]]
    name = "Datasets"
    url = "/Datasets-and-benchmark-code/"
    weight = 2